
#ifndef CHANNEL_0_PIN
#define CHANNEL_0_PIN		BRD_A3_PIN
#endif

#ifndef CHANNEL_1_PIN
#define CHANNEL_1_PIN		BRD_A4_PIN
#endif

#ifndef CHANNEL_2_PIN
#define CHANNEL_2_PIN		BRD_A5_PIN
#endif

#ifndef CHANNEL0_MODE_GPIO_PORT
#define CHANNEL0_MODE_GPIO_PORT 	BRD_A3_GPIO_PORT
#endif

#ifndef CHANNEL1_MODE_GPIO_PORT
#define CHANNEL1_MODE_GPIO_PORT 	BRD_A4_GPIO_PORT
#endif

#ifndef CHANNEL2_MODE_GPIO_PORT
#define CHANNEL2_MODE_GPIO_PORT 	BRD_A5_GPIO_PORT
#endif


#define S4344046_LA_CHAN0_CLR() {HAL_GPIO_WritePin(CHANNEL0_MODE_GPIO_PORT, CHANNEL_0_PIN, 0);}//Clear	LA	Channel	0	pin
#define S4344046_LA_CHAN0_SET() {HAL_GPIO_WritePin(CHANNEL0_MODE_GPIO_PORT, CHANNEL_0_PIN, 1);}//Set	LA	Channel	0	pin
#define S4344046_LA_CHAN1_CLR() {HAL_GPIO_WritePin(CHANNEL1_MODE_GPIO_PORT, CHANNEL_1_PIN, 0);}//Clear	LA	Channel	1	pin
#define S4344046_LA_CHAN1_SET() {HAL_GPIO_WritePin(CHANNEL1_MODE_GPIO_PORT, CHANNEL_1_PIN, 1);}//Set	LA	Channel	1	pin
#define S4344046_LA_CHAN2_CLR() {HAL_GPIO_WritePin(CHANNEL2_MODE_GPIO_PORT, CHANNEL_2_PIN, 0);}//Clear	LA	Channel	2	pin
#define S4344046_LA_CHAN2_SET() {HAL_GPIO_WritePin(CHANNEL2_MODE_GPIO_PORT, CHANNEL_2_PIN, 1);}//Set	LA	Channel	2	pin


void s4344046_sysmon_init();
